#!/bin/bash

# Configure dual displays.
# xrandr --output VGA-0 --left-of VGA-1
xsetroot -mod 4 4 -fg "#103142" -bg "#000000"

# Run the X composition manager because it makes Xmonad draw correctly in VirtualBox.
#xcompmgr &

dropbox start
~/realsync/sync
