#!/bin/zsh

# Add locations to the $PATH that actually exist.
PATH="/usr/local/bin:$PATH"
[ -d "/usr/texbin" ]                  && PATH="/usr/texbin:$PATH"
[ -d "/usr/local/share/npm/bin" ]     && PATH="/usr/local/share/npm/bin:$PATH"
[ -d "/usr/local/sbin" ]              && PATH="/usr/local/sbin:$PATH"
[ -d "$HOME/.local/bin" ]             && PATH="$PATH:$HOME/.local/bin"
[ -d "$HOME/.composer/vendor/bin" ]   && PATH="$PATH:$HOME/.composer/vendor/bin"
[ -d "/usr/local/go/bin" ]            && PATH="$PATH:/usr/local/go/bin"
[ -d "$HOME/Library/Python/2.7/bin" ] && PATH="$PATH:$HOME/Library/Python/2.7/bin"

# curl https://get.volta.sh | bash -s -- --skip-setup
if [ -d "$HOME/.volta" ]; then
  export VOLTA_HOME="$HOME/.volta"
  PATH="$VOLTA_HOME/bin:$PATH"
fi

# sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
if [ -d "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

if [ -d "$HOME/Library/Android/sdk" ]; then
  export ANDROID_HOME="$HOME/Library/Android/sdk"
fi

if [ -d "$ANDROID_HOME/tools" ]; then
  PATH="$PATH:${ANDROID_HOME}/tools"
fi

if [ -d "$ANDROID_HOME/platform-tools" ]; then
  PATH="$PATH:${ANDROID_HOME}/platform-tools"
fi

# Add my scripts directory to my path if it's there.
if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi

# Set up NPM locally-global paths
if [ ! -d "${HOME}/.node_modules" ]; then
  mkdir "${HOME}/.node_modules"
fi
NPM_PACKAGES="${HOME}/.node_modules"
PATH="$NPM_PACKAGES/bin:$PATH"
unset MANPATH
export MANPATH="${NPM_PACKAGES}/share/man:$(manpath)"

# Initialize rbenv if it exists on this system and isn't yet in our path.
# This prevents path duplication in tmux when a sub-shell runs this script
# again.
if [ -d $HOME/.rbenv/bin ] && [[ ! "$PATH" =~ "rbenv" ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"

  if [ -d "$HOME/.rbenv/plugins/ruby-build/bin" ]; then
    export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
  fi

  type rbenv >/dev/null 2>&1
  [[ "$?" == 0 ]] && eval "$(rbenv init -)"
fi

# Configure my Go workspace, if I have it.
if [ -d $HOME/go ]; then
  type go >/dev/null 2>&1
  if [[ "$?" == 0 ]]; then
    export GOPATH=$HOME/go
  fi
fi

## I don't know why this isn't configured by default.
export LD_LIBRARY_PATH=/usr/local/lib

# Removed because it starts *very* slowly; if I start doing more Node I'll
# end up back in here and see this and put it back. Maybe.
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Finally, remove duplicate PATH entries.
typeset -a paths result
paths=($path)

while [[ ${#paths} -gt 0 ]]; do
  p="${paths[1]}"
  shift paths
  [[ -z ${paths[(r)$p]} ]] && result+="$p"
done

export DISPLAY=$(ip route | grep default | awk '{print $3}'):0.0
clean_path=${(j+:+)result}
export PATH
export PATH=$clean_path
