#!/bin/zsh -f

# For tramp et al., don't do anything fancy.
if [[ "$TERM" == "dumb"  ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='$ '
  return
fi

if [ -f "$HOME/bin/antigen.zsh" ]; then
  source "$HOME/bin/antigen.zsh"
  antigen use oh-my-zsh

  # Do not load these in SSH sessions.
  if [ -z "$SSH_CLIENT" ]; then
    antigen bundle tmux
    export ZSH_TMUX_AUTOSTART=true
    export ZSH_TMUX_FIXTERM=true

    antigen bundle gpg-agent
    antigen bundle keychain
    zstyle :omz:plugins:keychain options --quiet

    antigen bundle python
    antigen bundle "MichaelAquilina/zsh-autoswitch-virtualenv"
  fi

  antigen bundle common-aliases
  antigen bundle emacs
  antigen bundle starship
  antigen bundle sudo
  antigen bundle timer
  antigen bundle vi-mode

  antigen apply
fi

source ~/.zsh_functions

# Reattach or start a new Tmux.
# This function name is short because I want to call it this way
# interactively.
#t

# Set my terminal if I'm not in tmux.
[[ "$TMUX" == "" ]] && TERM=rxvt-unicode-256color

# Configure zsh options #######################################################
setopt autolist       # Display completion candidates immediately.
setopt cdablevars     # When an argument should be a dir but is not one,
                      # expand it as if it started with ~ (see below).
setopt autonamedirs   # Any parameter that is set to an abosolute directory
                      # name automatically becomes a name for that directory
                      # in the form ~param.
setopt histignoredups # Do not record a command in the history if it is a
                      # duplicate of the previous one.
setopt listtypes      # When listing files that are possible completions,
                      # indicate their types with a trailing character.
setopt nolistbeep     # No bell on ambiguous completion!!

# While selecting from menu completion, pressing enter accepts the selection
# and executes the command.
bindkey -M menuselect '^M' .accept-line

### Aliases.
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias ssh='ssh -A'
alias cpr="rsync -aP"

command -v xdg-open >/dev/null 2>&1 && alias open="xdg-open"

export EDITOR="vim"
export VISUAL="vim"

## Heuristic to compute location because I am lazy.
if [[ `whoami` == "airborne" ]]; then
  export MY_LOCATION="home"
else
  export MY_LOCATION="work"
fi

if [ -f "$HOME/.zshrc_$MY_LOCATION" ]; then
  source "$HOME/.zshrc_$MY_LOCATION"
fi

motd
# vim: set et ts=2 sw=2 tw=79 cc=+1 :
